# Используем официальный образ Nginx для статического веб-сервера
FROM nginx:alpine

# Копируем файлы фронтенда в папку /usr/share/nginx/html
COPY index.html /usr/share/nginx/html/
COPY index.js /usr/share/nginx/html/
