replicaCount: 1

image:
  repository: postgres
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  size: 10Gi

postgresql:
  username: user
  password: password
  database: mydatabase
