apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000
  selector:
    app: backend
